# Generated by Django 6.0.5 on 2026-06-02 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('summary', models.CharField(max_length=500, verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('checked_in', 'Заселён'), ('checked_out', 'Выселен'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Скидка (руб.)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого (руб.)')),
                ('guests_count', models.PositiveIntegerField(default=1, verbose_name='Кол-во гостей')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('passport', models.CharField(blank=True, max_length=20, verbose_name='Паспорт')),
                ('has_children', models.BooleanField(default=False, verbose_name='Есть дети')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('founded_year', models.PositiveIntegerField(verbose_name='Год основания')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип')),
                ('stars', models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Звёзды (1-5)')),
                ('history', models.TextField(blank=True, verbose_name='История')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'О гостинице',
                'verbose_name_plural': 'О гостинице',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('cleaner', 'Горничная'), ('security', 'Охрана'), ('concierge', 'Консьерж')], max_length=50, verbose_name='Должность')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата (руб.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Словарь терминов',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма (руб.)')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('online', 'Онлайн'), ('transfer', 'Перевод')], default='card', max_length=20, verbose_name='Способ оплаты')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discount_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка %')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-valid_to'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Вместимость (чел.)')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена за сутки (руб.)')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='Этаж')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь (м²)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('amenities', models.TextField(blank=True, verbose_name='Удобства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Фото')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('comfort', models.CharField(choices=[('standard', 'Стандартный'), ('semi_lux', 'Полулюкс'), ('lux', 'Люкс'), ('suite', 'Апартаменты')], default='standard', max_length=20, verbose_name='Комфортность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
